apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: fresh-delivery
  labels:
    app: admin-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
        version: v1
    spec:
      containers:
      - name: admin-frontend
        image: ghcr.io/your-org/fresh-delivery/admin-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "https://api.biangqiang.com"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
  namespace: fresh-delivery
  labels:
    app: admin-frontend
spec:
  selector:
    app: admin-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
---
# HorizontalPodAutoscaler for frontend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-frontend-hpa
  namespace: fresh-delivery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
# 测试环境前端部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: fresh-delivery-staging
  labels:
    app: admin-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
        version: v1
    spec:
      containers:
      - name: admin-frontend
        image: ghcr.io/your-org/fresh-delivery/admin-frontend:staging
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "https://staging.biangqiang.com/api"
        - name: NODE_ENV
          value: "staging"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
  namespace: fresh-delivery-staging
  labels:
    app: admin-frontend
spec:
  selector:
    app: admin-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP