apiVersion: v1
kind: Secret
metadata:
  name: fresh-delivery-secrets
  namespace: fresh-delivery
type: Opaque
data:
  # 数据库凭证 (使用base64编码)
  MYSQL_USERNAME: cm9vdA== # root
  MYSQL_PASSWORD: UGFzc3dvcmQxMjMh # Password123!
  
  # Redis密码 (使用base64编码)
  REDIS_PASSWORD: UmVkaXNQYXNzd29yZDEyMyE= # RedisPassword123!
  
  # JWT密钥 (使用base64编码)
  JWT_SECRET: YmlhbmdxaWFuZy1mcmVzaC1kZWxpdmVyeS1qd3Qtc2VjcmV0LWtleS0yMDIz # biangqiang-fresh-delivery-jwt-secret-key-2023
  
  # 微信小程序密钥 (使用base64编码)
  WECHAT_SECRET: d2VjaGF0LXNlY3JldC1rZXk= # wechat-secret-key
  
  # 支付密钥 (使用base64编码)
  PAYMENT_KEY: cGF5bWVudC1zZWNyZXQta2V5 # payment-secret-key
  
  # 邮件凭证 (使用base64编码)
  MAIL_USERNAME: YWRtaW5AYmlhbmdxaWFuZy5jb20= # admin@biangqiang.com
  MAIL_PASSWORD: bWFpbC1wYXNzd29yZC0xMjM= # mail-password-123
  
  # 短信API密钥 (使用base64编码)
  SMS_ACCESS_KEY: c21zLWFjY2Vzcy1rZXk= # sms-access-key
  SMS_ACCESS_SECRET: c21zLWFjY2Vzcy1zZWNyZXQ= # sms-access-secret
  
  # OSS密钥 (使用base64编码)
  OSS_ACCESS_KEY: b3NzLWFjY2Vzcy1rZXk= # oss-access-key
  OSS_ACCESS_SECRET: b3NzLWFjY2Vzcy1zZWNyZXQ= # oss-access-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: fresh-delivery-secrets
  namespace: fresh-delivery-staging
type: Opaque
data:
  # 数据库凭证 (使用base64编码)
  MYSQL_USERNAME: cm9vdA== # root
  MYSQL_PASSWORD: U3RhZ2luZ1Bhc3N3b3JkMTIzIQ== # StagingPassword123!
  
  # Redis密码 (使用base64编码)
  REDIS_PASSWORD: U3RhZ2luZ1JlZGlzUGFzc3dvcmQxMjMh # StagingRedisPassword123!
  
  # JWT密钥 (使用base64编码)
  JWT_SECRET: YmlhbmdxaWFuZy1mcmVzaC1kZWxpdmVyeS1zdGFnaW5nLWp3dC1zZWNyZXQta2V5LTIwMjM= # biangqiang-fresh-delivery-staging-jwt-secret-key-2023
  
  # 微信小程序密钥 (使用base64编码)
  WECHAT_SECRET: d2VjaGF0LXN0YWdpbmctc2VjcmV0LWtleQ== # wechat-staging-secret-key
  
  # 支付密钥 (使用base64编码)
  PAYMENT_KEY: cGF5bWVudC1zdGFnaW5nLXNlY3JldC1rZXk= # payment-staging-secret-key
  
  # 邮件凭证 (使用base64编码)
  MAIL_USERNAME: c3RhZ2luZ0BiaWFuZ3FpYW5nLmNvbQ== # staging@biangqiang.com
  MAIL_PASSWORD: c3RhZ2luZy1tYWlsLXBhc3N3b3JkLTEyMw== # staging-mail-password-123
  
  # 短信API密钥 (使用base64编码)
  SMS_ACCESS_KEY: c3RhZ2luZy1zbXMtYWNjZXNzLWtleQ== # staging-sms-access-key
  SMS_ACCESS_SECRET: c3RhZ2luZy1zbXMtYWNjZXNzLXNlY3JldA== # staging-sms-access-secret
  
  # OSS密钥 (使用base64编码)
  OSS_ACCESS_KEY: c3RhZ2luZy1vc3MtYWNjZXNzLWtleQ== # staging-oss-access-key
  OSS_ACCESS_SECRET: c3RhZ2luZy1vc3MtYWNjZXNzLXNlY3JldA== # staging-oss-access-secret