# 文件上传配置
upload:
  # 上传文件存储路径
  path: f:/code/backend/uploads
  # 图片上传配置
  image:
    # 允许的图片格式
    allowed-types:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
    # 最大文件大小（字节）
    max-size: 5242880  # 5MB
    # 图片质量压缩
    compress:
      enabled: true
      quality: 0.8
    # 缩略图配置
    thumbnail:
      enabled: true
      width: 300
      height: 300
  # 批量上传配置
  batch:
    max-files: 10
    max-total-size: 52428800  # 50MB

# 静态资源配置
static:
  # 静态资源访问路径
  resource-handler: /uploads/**
  # 静态资源存储位置
  resource-locations: file:f:/code/backend/uploads/
  # 缓存配置
  cache:
    enabled: true
    max-age: 3600  # 1小时

# 图片服务配置
image:
  # 默认图片配置
  default:
    product: /images/default-product.svg
    category: /images/tab/category.png
    avatar: /images/default-avatar.svg
    banner: /images/logo.svg
  # CDN配置（可选）
  cdn:
    enabled: false
    domain: ""
    access-key: ""
    secret-key: ""
    bucket: ""
  # 图片处理配置
  processing:
    # 水印配置
    watermark:
      enabled: false
      text: "边墙鲜送"
      position: bottom-right
      opacity: 0.5
    # 自动压缩
    auto-compress:
      enabled: true
      max-width: 1920
      max-height: 1080
      quality: 0.85